[2024-03-06T10:58:49.475-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T10:58:49.480-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T10:58:49.480-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T10:58:49.496-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-02 00:00:00+00:00
[2024-03-06T10:58:49.499-0300] {standard_task_runner.py:60} INFO - Started process 18773 to run task
[2024-03-06T10:58:49.501-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpqvtiipxp']
[2024-03-06T10:58:49.503-0300] {standard_task_runner.py:88} INFO - Job 9: Subtask AAPL
[2024-03-06T10:58:49.547-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T10:58:49.601-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T10:58:50.247-0300] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T10:58:50.250-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T10:58:50.254-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240102T000000, start_date=20240306T135849, end_date=20240306T135850
[2024-03-06T10:58:50.319-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T10:58:50.334-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:08.453-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:04:08.484-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:04:08.484-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:08.558-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:04:08.584-0300] {standard_task_runner.py:60} INFO - Started process 39023 to run task
[2024-03-06T12:04:08.738-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp1wl85xvl']
[2024-03-06T12:04:08.742-0300] {standard_task_runner.py:88} INFO - Job 7: Subtask AAPL
[2024-03-06T12:04:09.393-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:09.940-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:04:11.241-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:11.738-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240102T000000, start_date=20240306T150408, end_date=20240306T150411
[2024-03-06T12:04:15.388-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 39023)
[2024-03-06T12:04:15.471-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:15.528-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:15:34.535-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:15:34.572-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:15:34.573-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:15:34.635-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:15:34.646-0300] {standard_task_runner.py:60} INFO - Started process 46528 to run task
[2024-03-06T12:15:34.664-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpsy4vsa2p']
[2024-03-06T12:15:34.690-0300] {standard_task_runner.py:88} INFO - Job 145: Subtask AAPL
[2024-03-06T12:15:34.885-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:15:35.244-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:15:36.936-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:15:41.026-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240102T000000, start_date=20240306T151534, end_date=20240306T151541
[2024-03-06T12:15:41.229-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 46528)
[2024-03-06T12:15:41.312-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:15:42.104-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:16:56.663-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:16:56.672-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:16:56.673-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:16:56.688-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:16:56.693-0300] {standard_task_runner.py:60} INFO - Started process 48543 to run task
[2024-03-06T12:16:56.695-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp82f1ih57']
[2024-03-06T12:16:56.697-0300] {standard_task_runner.py:88} INFO - Job 202: Subtask AAPL
[2024-03-06T12:16:56.759-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:16:56.856-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:16:57.935-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:16:57.951-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240102T000000, start_date=20240306T151656, end_date=20240306T151657
[2024-03-06T12:16:57.967-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 48543)
[2024-03-06T12:16:57.996-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:16:58.037-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T14:38:38.355-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:38:38.367-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:38:38.368-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T14:38:38.382-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-02 00:00:00+00:00
[2024-03-06T14:38:38.387-0300] {standard_task_runner.py:60} INFO - Started process 82676 to run task
[2024-03-06T14:38:38.389-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpcus0uk8m']
[2024-03-06T14:38:38.390-0300] {standard_task_runner.py:88} INFO - Job 256: Subtask AAPL
[2024-03-06T14:38:38.453-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T14:38:38.549-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T14:38:40.743-0300] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T14:38:40.746-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T14:38:40.761-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240102T000000, start_date=20240306T173838, end_date=20240306T173840
[2024-03-06T14:38:40.819-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T14:38:40.842-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
