[2024-03-06T11:00:55.319-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:55.324-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:55.324-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T11:00:55.338-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-16 00:00:00+00:00
[2024-03-06T11:00:55.342-0300] {standard_task_runner.py:60} INFO - Started process 19831 to run task
[2024-03-06T11:00:55.345-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp7t2w3a0m']
[2024-03-06T11:00:55.346-0300] {standard_task_runner.py:88} INFO - Job 51: Subtask GOOG
[2024-03-06T11:00:55.377-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T11:00:55.430-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T11:00:56.003-0300] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-03-06T11:00:56.005-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T11:00:56.013-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240116T000000, start_date=20240306T140055, end_date=20240306T140056
[2024-03-06T11:00:56.042-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T11:00:56.053-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:28.634-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.673-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.674-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:28.720-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:04:28.730-0300] {standard_task_runner.py:60} INFO - Started process 40094 to run task
[2024-03-06T12:04:28.750-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpv_hi9wbk']
[2024-03-06T12:04:28.753-0300] {standard_task_runner.py:88} INFO - Job 45: Subtask GOOG
[2024-03-06T12:04:29.003-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:29.335-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:04:30.342-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:30.647-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240116T000000, start_date=20240306T150428, end_date=20240306T150430
[2024-03-06T12:04:30.755-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 40094)
[2024-03-06T12:04:30.843-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:30.911-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
