[2024-03-06T11:00:50.193-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:50.199-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:50.199-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T11:00:50.214-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-16 00:00:00+00:00
[2024-03-06T11:00:50.218-0300] {standard_task_runner.py:60} INFO - Started process 19793 to run task
[2024-03-06T11:00:50.220-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpfs5t50ht']
[2024-03-06T11:00:50.221-0300] {standard_task_runner.py:88} INFO - Job 49: Subtask AAPL
[2024-03-06T11:00:50.255-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T11:00:50.307-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T11:00:50.898-0300] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-03-06T11:00:50.900-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T11:00:50.905-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240116T000000, start_date=20240306T140050, end_date=20240306T140050
[2024-03-06T11:00:50.958-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T11:00:50.971-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:28.693-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.725-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.726-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:28.776-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:04:28.799-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpc0ozqlem']
[2024-03-06T12:04:28.802-0300] {standard_task_runner.py:88} INFO - Job 48: Subtask AAPL
[2024-03-06T12:04:28.793-0300] {standard_task_runner.py:60} INFO - Started process 40103 to run task
[2024-03-06T12:04:29.010-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:29.328-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:04:29.938-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:30.659-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240116T000000, start_date=20240306T150428, end_date=20240306T150430
[2024-03-06T12:04:30.765-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 40103)
[2024-03-06T12:04:30.888-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:31.272-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
